from __future__ import annotations

import json
import os
import re
import threading
from datetime import datetime
from pathlib import Path
from typing import Any, Iterator

from .extract import canonical_status_url, status_key

STATUS_IN_TEXT = re.compile(r"https?://(?:x|twitter)\.com/[\w.]+/status(?:es)?/\d+")


class SeenStore:
    def __init__(self, path: Path) -> None:
        self.path = Path(path)
        self._keys: dict[str, dict[str, Any]] = {}
        self._lock = threading.Lock()
        self._dirty = False

    def load(self) -> int:
        if not self.path.exists():
            return 0
        try:
            data = json.loads(self.path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return 0
        if isinstance(data, dict):
            entries = data.get("seen", data)
            if isinstance(entries, dict):
                self._keys = {str(k): dict(v) if isinstance(v, dict) else {} for k, v in entries.items()}
        return len(self._keys)

    def seed_from_markdown(self, markdown_path: Path) -> int:
        if not Path(markdown_path).exists():
            return 0
        content = Path(markdown_path).read_text(encoding="utf-8", errors="ignore")
        added = 0
        for url in STATUS_IN_TEXT.findall(content):
            key = status_key(url) or status_key(canonical_status_url(url))
            if key and key not in self._keys:
                self._keys[key] = {"source": "legacy_markdown"}
                added += 1
                self._dirty = True
        return added

    def __contains__(self, key: str) -> bool:
        return key in self._keys

    def add(self, key: str, **meta: Any) -> None:
        with self._lock:
            if key in self._keys:
                return
            self._keys[key] = {"first_seen": datetime.now().isoformat(timespec="seconds"), **meta}
            self._dirty = True

    def save(self) -> None:
        if not self._dirty:
            return
        self.path.parent.mkdir(parents=True, exist_ok=True)
        temp = self.path.with_suffix(".tmp")
        temp.write_text(json.dumps({"seen": self._keys}, indent=1, sort_keys=True), encoding="utf-8")
        os.replace(temp, self.path)
        self._dirty = False

    def __len__(self) -> int:
        return len(self._keys)


def append_jsonl(path: Path, record: dict[str, Any]) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(record, ensure_ascii=False) + "\n")
        handle.flush()


def read_jsonl(path: Path) -> Iterator[dict[str, Any]]:
    path = Path(path)
    if not path.exists():
        return iter(())
    def generator() -> Iterator[dict[str, Any]]:
        with path.open("r", encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if not line:
                    continue
                try:
                    yield json.loads(line)
                except json.JSONDecodeError:
                    continue
    return generator()


class MarkdownDigest:
    def __init__(self, path: Path, title: str) -> None:
        self.path = Path(path)
        self.title = title
        self._last_day: str | None = None
        if not self.path.exists():
            self.path.parent.mkdir(parents=True, exist_ok=True)
            self.path.write_text(
                f"# {title}\n\nAuto-generated by xmaxxing. Do not edit by hand.\n\n",
                encoding="utf-8",
            )

    def append(self, entry: dict[str, Any]) -> None:
        stamp = entry.get("scraped_at") or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        day = stamp[:10]
        lines: list[str] = []
        if day != self._last_day:
            lines.append(f"\n### {day}\n")
            self._last_day = day
        title = " — ".join(filter(None, [entry.get("company") or "", (entry.get("roles") or [""])[0]])) or entry.get("handle", "post")
        lines.append(f"\n## {title}\n")
        lines.append(f"- **Posted by:** {entry.get('display_name', '')} @{entry.get('handle', '')} · {entry.get('relative_time', '')}\n")
        lines.append(f"- **Tweet:** {entry.get('tweet_url', '')}\n")
        for label, key in (("Locations", "locations"), ("Compensation", "comp"), ("Eligibility", "eligibility"), ("Deadline", "deadline")):
            value = entry.get(key)
            rendered = self._render_value(value)
            if rendered:
                lines.append(f"- **{label}:** {rendered}\n")
        apply_urls = entry.get("apply_urls") or []
        if apply_urls:
            lines.append("- **Apply:**\n")
            for url in apply_urls:
                lines.append(f"  - {url}\n")
        if entry.get("reply_urls"):
            lines.append(f"- **From replies:** {', '.join(entry['reply_urls'])}\n")
        score = entry.get("score")
        signals = entry.get("signals")
        if score is not None:
            suffix = f" ({'+'.join(signals)})" if signals else ""
            lines.append(f"- **Score:** {score}{suffix}\n")
        lines.append("- **Text:**\n")
        for line in (entry.get("text") or "").splitlines():
            lines.append(f"  > {line}\n" if line.strip() else "  >\n")
        lines.append("\n---\n")
        with self.path.open("a", encoding="utf-8") as handle:
            handle.write("".join(lines))

    @staticmethod
    def _render_value(value: Any) -> str:
        if value is None:
            return ""
        if isinstance(value, list):
            return ", ".join(str(item) for item in value if item)
        if isinstance(value, dict):
            return str(value.get("raw") or "")
        return str(value)